---
title: 23周：June05 Science, June04 Nature
author: Zhuoer Dong
date: '2020-06-07'
tags:
  - paper
slug: 2020-23
---



# Science - Research Articles

1. Unexpected conservation and global transmission of agrobacterial virulence plasmids
   居然是保守的
1. The structure of human CST reveals a decameric assembly bound to telomeric DNA
   电镜，de novo 搭结构
1. *Photoelectron spectra of alkali metal–ammonia microjets: From blue electrolyte to bronze metal
1. Giant thermopower of ionic gelatin near room temperature
   依靠环境热量发电，让可穿戴设备摆脱线缆和电池



# Science - Reports

1. Iridium-catalyzed acid-assisted asymmetric hydrogenation of oximes to hydroxylamines
1. Nontargeted mass-spectral detection of chloroperfluoropolyether carboxylates in New Jersey soils
   检测 PFAS 环境残留
1. Restoring light sensitivity using tunable near-infrared sensors
   用 gold nanorods 和 TRP channels 人造视细胞
1. A fractional corner anomaly reveals higher-order topology
1. Thresholds of mangrove survival under rapid sea level rise
   如果海平面上涨超过 6.1mm/year，红树林的堆积速度就赶不上了
1. PIRs mediate innate myeloid cell memory to nonself MHC molecules
   先天免疫也有记忆效应
1. MTOR signaling orchestrates stress-induced mutagenesis, facilitating adaptive evolution in cancer
   肿瘤靠压力诱导的突变来抵抗药物
1. NELL2-mediated lumicrine signaling through OVCH2 is required for male fertility
1. Barcoded microbial system for high-resolution object provenance
   用合成孢子，快速精确地检测物体起源
1. Seafloor microplastic hotspots controlled by deep-sea circulation
   传送氧气和养料的洋流，也传送微塑料颗粒



# Nature

1. Observation of Laughlin states made of light
1. Controlling free electrons with optical whispering-gallery modes
1. Coherent interaction between free electrons and a photonic cavity
1. *Design of robust superhydrophobic surfaces
   一材两致（纳米结构+微结构）实现防雾、耐磨损兼得
1. Selective prebiotic formation of RNA pyrimidine and DNA purine nucleosides
   在生命起源之前，也许 DNA 和 RNA 是共同存在的，起码作者证明了化学合成是可能的
1. Displaced cratonic mantle concentrates deep carbon during continental rifting
1. Repositioning of the global epicentre of non-optimal cholesterol
   高胆固醇从西方国家转移到了发展中国家
1. The nature of Neanderthal introgression revealed by 27,566 Icelandic genomes
   人类与尼安德特人的总突变率一样，但是不同突变类型的频率不同
1. Variability in the analysis of a single neuroimaging dataset by many teams
   70的团队的workflow各不一样
1. C9orf72 suppresses systemic and neural inflammation induced by gut bacteria
1. Landscape and function of multiple mutations within individual oncogenes
1. Phase and context shape the function of composite oncogenic mutations
1. Anti-PfGARP activates programmed cell death of parasites and reduces severe malaria
   靶向PfGARP的抗体能抑制疟疾，在有些人中天然存在
1. Mouse models of neutropenia reveal progenitor-stage-specific defects
1. LEM2 phase separation promotes ESCRT-mediated nuclear envelope reformation
1. Convergent genes shape budding yeast pericentromeres
1. Multilayered mechanisms ensure that short chromosomes recombine in meiosis
   小染色体必须有同源重组（否则会分配不均），那么 DSB（双链断裂）就不是随机分布的（随机的话小染色体概率太小，很可能就没有了），作者在酵母中发现了调节这一过程的生理机制
1. Structure and mechanism of the mitochondrial Ca2+ uniporter holocomplex
