---
title: 25周：June19 Science, June18 Nature
author: Zhuoer Dong
date: '2020-09-17'
tags:
  - paper
slug: 2020-25
---



# Science - Research Articles

1. Manipulating synthetic optogenetic odors reveals the coding logic of olfactory perception
   用光遗传学控制嗅觉细胞，输入参数化的 pattern，测量小鼠的反应，从而搭建model来解释嗅觉如何产生
1. Gas chromatography–mass spectrometry analyses of encapsulated stable perovskite solar cells
   钛铁矿太阳能细胞，色谱-质谱联用，分析热刺激后的代谢物，证明 polymer/glass 包裹能抑制这种 outgass
1. Meissner corpuscles and their spatially intermingled afferents underlie gentle touch perception
   触觉必须要有 Meissner corpuscle，末端有两种机械感受细胞，交错排列
1. Structure-based design of antiviral drug candidates targeting the SARS-CoV-2 main protease
   靶向Mpro（病毒复制和转录），X-ray 1.5A，aldehyde基团共价结合 Cys145，其中一种毒性低
1. Different genetic barriers for resistance to HA stem antibodies in influenza H3 and H1 viruses
   以前认为靶向HA高保守的 stem 区域就高枕无忧，但突变筛选发现 H3 亚型很容易产生抗药性（H1 就较难，因为结构不一样），甚至自然群体就有这种突变
1. Landscape-scale forest loss as a catalyst of population and biodiversity change
   森林流失加速了局部物种多样性的变化速率，甚至延时 50年。



# Science - Reports

1. Making ultrastrong steel tough by grain-boundary delamination
   **分层工艺生产超高强度钢
1. Microfluidic electrochemistry for single-electron transfer redox-neutral reactions
1. 3D fault architecture controls the dynamism of earthquake swarms
   深度学习研究地震 swarm 演化
1. Rapid implementation of mobile technology for real-time epidemiology of COVID-19
   开发 App 收集新冠流行病学数据
1. Measles virus and rinderpest virus divergence dated to the sixth century BCE
   麻疹与牛瘟病毒在 6世纪前演化分叉，也许和大城市兴起重合
1. T cells with dysfunctional mitochondria induce multimorbidity and premature senescence
   线粒体缺陷的 T cell 会导致细胞因子积累，（就像慢性发炎一样）引发多种老年特征，导致早死。
1. Information arms race explains plant-herbivore chemical communication in ecological communities
   用信息论解释植物与食草动物 arm race
1. Structural evidence for a dynamic metallocofactor during N2 reduction by Mo-nitrogenase
   1.83A 固氮酶晶体结构，揭示金属辅因子
1. Partitioning of cancer therapeutics in nuclear condensates
   细胞核中通过相分离形成的聚合体，会富集抗肿瘤药，影响药代动力学



# Nature

1. Periodic activity from a fast radio burst source
   发现一种周期性的快射电暴来源
1. Resolving acceleration to very high energies along the jet of Centaurus A
1. Frequency combs induced by phase turbulence
1. Integrated turnkey soliton microcombs
1. Hierarchically structured diamond composite with exceptional toughness
   把其它材料的用到的一些方法应用到砖石中来，硬度和韧性我都要
1. Imaging single glycans
   之前寡糖成像都是 NMR 等间接手段，作者用扫描遂穿显微镜直接对单分子进行成像
1. Emergent constraint on Arctic Ocean acidification in the twenty-first century
   全球变暖对北冰洋酸化的影响速率更快
1. A dynastic elite in monumental Neolithic society
   新石器时代，修纪念碑，以前认为可能存在阶层分化，作者 sequence genome 证明了血缘关系，结合地理位置
1. Population flow drives spatio-temporal distribution of COVID-19 in China
   分析了一月1~24号从武汉出发的人口流动数据（手机记录），发现与新冠发病率符合得很好
1. Potential circadian effects on translational failure for neuroprotection
   神经保护剂人鼠不同，作者发现昼夜节律的不同可能其重要作用，解释分子机制
1. Hair-bearing human skin generated entirely from pluripotent stem cells
   类器官培养系统产生皮肤
1. Single-cell and spatial transcriptomics reveal somitogenesis in gastruloids
   体发生 in 胃甾体，与小鼠胚胎很像，体外高通量研究发育
1. An in vitro model of early anteroposterior organization during human development
1. CRISPR screen in regulatory T cells reveals modulators of Foxp3
   筛出 Usp22 正调控，Rnf20负调控
1. BCR selection and affinity maturation in Peyer’s patch germinal centres
   B细胞种系中心大部分是暂时的，在小肠Peyer确实长期的，作者分析了 BCR 库和体细胞超突变 pattern
1. Ensuring meiotic DNA break formation in the mouse pseudoautosomal region
   性染色体的 PAR 区域，作者呈现了动态超结构，发现了顺式-，反式-因子，来控制双链断裂只发生在该区域
1. RIC-seq for global in situ profiling of RNA–RNA spatial interactions
   用酶把空间上接近的RNA连接起来
1. Determination of RNA structural diversity and its role in HIV-1 RNA splicing
   HIV-1 病毒，alternate fold 决定了可变剪接 isoform 比例
1. A lower X-gate in TASK channels traps inhibitors within the vestibule
 