---
title: 41周：Oct09 Science, Oct08 Nature
author: Zhuoer Dong
date: '2020-10-12'
slug: 2020-41
categories: []
tags:
  - paper
authors: []
---



# Science - Research Articles

1. The heterogeneity of persistent slip band nucleation and evolution in metals at the micrometer scale
   讲金属疲劳的形成机制，有点像单细胞，说 micrometer-scale 与之前的 bulk scale 不一样
2. Conformational states dynamically populated by a kinase determine its function
   用核磁共振研究 Abl kinase 在活跃构象和两种离散的非活跃构象之间的转变，还做了原癌基因和药物作用的机理，就是不知道冷冻电镜能不能做出来
3. Coupling of NMDA receptors and TRPM4 guides discovery of unconventional neuroprotectants
   小分子影响 NMDAR 与 TRPM4 的结合，但不干扰前者诱发的钙信号，有望治疗神经退化
4. Reconstitution and visualization of HIV-1 capsid-dependent replication and integration in vitro
   HIV-1 的复制和整合发生在 "deep within cells"所以看不清楚，作者用体外体系来研究，揭示了 capsid 的重要性
5. Neutrophilic inflammation in the respiratory mucosa predisposes to RSV infection
   如果在感染 RSV 之间，有黏膜噬中性细胞发炎的话，就更容易患病
6. Black phosphorus composites with engineered interfaces for high-rate high-capacity lithium storage
   黑磷作为阳极，让锂电池充电快、容量高
7. Spacetime from bits
   量子重力，之前认为的非重力系统可以被替换成 arbitrarily large collection of noninteracting systems (“bits”)。纯理论，只有示意图
8. In situ structural analysis of SARS-CoV-2 spike reveals flexibility mediated by three hinges
   TOM和分子动力学模拟，spike蛋白的头有三个铰链，产生很高的自由度来 scan 宿主细胞表面，包被大量糖基化来躲避抗体
9. The mole genome reveals regulatory rearrangements associated with adaptive intersexuality
   整合基因组、转录组、表观组等数据集，揭示了非编码序列变异的表型（系统发育，鼹鼠性腺，knock-in）



# Science - Reports

1. Electro-inductive effect: Electrodes as functional groups with tunable electronic properties
   把官能团固定在金电极上，不同电压产生不同效果
2. Increased extinction in the emergence of novel ecological communities
   在向新的群落转变的过程中，灭绝、起源等的速率比一般群落快很多
3. Cryo-EM with sub–1 Å specimen movement
   证明了 particle 移动是由冰的屈曲和变形导致的，引进了一种方法消除屈曲，使移动小于 1A
4. WUSCHEL triggers innate antiviral immunity in plant stem cells
   WUSCHEL 介导的广谱先天免疫，植物干细胞抵抗病毒的机制
5. Clean 2D superconductivity in a bulk van der Waals superlattice
6. Influenza vaccine–induced human bone marrow plasma cells decline within a year after vaccination
   骨髓血浆细胞（BMPC），在疫苗接种 4周后达到峰值，但一年后又和之前一样了
7. MHC class II transactivator CIITA induces cell resistance to Ebola virus and SARS-like coronaviruses
   用转座子介导的基因激活做筛选，发现CIITA能抵抗埃博拉，其下游基因 CD74 p41 还能抵抗新冠
8. Alternating sequences of future and past behavior encoded within hippocampal theta oscillations
   海马 CA1 place cell 在 theta 振荡过程中天生会产生正向和反向序列，解释了回顾性评价的神经回路基础



# Nature

01. Four annular structures in a protostellar disk less than 500,000 years old
02. Emergent electromagnetic induction in a helical-spin magnet
    传统电导是靠线圈，限制了微型化，作者用量子机制，相同电压只需要百万分之一体积
03. Near-perfect photon utilization in an air-bridge thermophotovoltaic cell
    热能直接发电（如废热），但是光子能量太低，作者在薄膜 cell 之间加了一层空气，实现低能光子几乎完美发反射
04. Intercepting fleeting cyclic allenes with asymmetric nickel catalysis
    环有机分子，催化不对称反应，两种新机制控制立体化学，这些传统想避免的中间产物有着更广泛的应用可能性
05. A comprehensive quantification of global nitrous oxide sources and sinks
    全球氮氧化物循环清单，人为排放最多来自农田。新兴经济体的排放在增加
06. Local exposure to inequality raises support of people of low wealth for taxing the wealthy
    在个体水平，穷人意识到不平等（看见富人）后，会希望像富人收更多的税
07. Innovations present in the primate interneuron repertoire
    三灵长动物+老鼠+水貂，单细胞核RNA-seq，中间神经元，从进化上横向比较
08. A hypothala一度换回mic novelty signal modulates hippocampal memory
    大脑对新信号给予更高的关注，作者鉴定上乳头核SuM是新的hub，语义和社会信号分别通过两条不同的通路传给下丘脑。
09. Phenotypic landscape of intestinal organoid regeneration
    结合定量成像和RNA-seq，分析了大量的小肠类器官，阐明了基因相互作用如何调节表型
10. The maternal microbiome modulates fetal neurodevelopment in mice
    母亲肠道微生物组影响胎儿产前大脑发育，微生物调控的代谢产物作用于神经元
11. Na+ controls hypoxic signalling by the mitochondrial respiratory chain
    地球人都知道Ca2+参与了低氧反应，作者证明Na+也参与了，Na+与磷脂作用降低线粒体内膜流动性，减少自由泛醌的移动性，最终在复合体III产生超氧化物
12. Repeat expansions confer WRN dependence in microsatellite-unstable cancers
    微卫星不稳定的癌细胞在敲除WRN基因后死亡，作者发现发现原因，TA双核苷酸重复扩张，形成非B型DNA二级结构，需要WRN解旋，否则会被核酸酶切割
13. Tumoural activation of TLR3–SLIT2 axis in endothelium drives metastasis
    癌细胞使用了天然的信号通路，释放双链RNA，TLR3受体上调SLIT2基因表达，SLIT2蛋白建立起血管上皮细胞-癌细胞由高到低的浓度梯度，促使癌细胞转移。人为建立或破坏这一梯度即可促进或抑制转移。
14. CTCF orchestrates long-range cohesin-driven V(D)J recombinational scanning
    线性DAG扫描调节远端V~H~使用率
15. Structural basis of salicylic acid perception by Arabidopsis NPR proteins
    水杨酸SA是抗病植物激素，NPR蛋白是受体，作者阐明了二者是如何结合的，晶体结构，SA结合core经历了很大的构象remodelling 
16. Structures of fungal and plant acetohydroxyacid synthases
    乙酰乳酸合成酶的结构，催化亚基和调节亚基的交互，激活和反馈抑制的通路
