---
title: 43周：Nov06 Science, Nov05 Nature
author: Zhuoer Dong
date: '2020-11-09'
slug: 2020-45
categories: []
tags:
  - paper
authors: []
---



# Science - Research Articles

1. Behavioral nudges reduce failure to appear for court
   低程度冒犯的被告，更人性化的法律传票可以使不出庭的人（会被逮捕）减少 13~21%
2. Deep conservation of the enhancer regulatory code in animals
   从海绵开始就存在的古老增强子
3. Resource conservation manifests in the genetic code
   遗传密码也懂可持续发展
4. Enigmatic amphibians in mid-Cretaceous amber were chameleon-like ballistic feeders
   Albanerpetontid 琥珀标本，像变色龙一样坐等食物上门、弹出舌头
5. Epidemiology and transmission dynamics of COVID-19 in two Indian states
   新冠在穷人中是怎么传播的



# Science - Reports

1. Large-area low-noise flexible organic photodiodes for detecting faint visible light
   有机发光二极管
2. Nonlinearity-induced photonic topological insulator
   拓扑绝缘体，光强够大时进入非线性领域
3. Global food system emissions could preclude achieving the 1.5° and 2°C climate change targets
   光是全球食物系统排放的碳，就可以为巴黎协定的 2℃目标宣告死刑
4. Rational design of layered oxide materials for sodium-ion batteries
   通过计算预测电极材料的化学性质
5. Ecological insights from three decades of animal movement tracking across a changing Arctic
   北极生物移动数据集
6. Phasing of millennial-scale climate variability in the Pacific and Atlantic Oceans
   海湾的放射性碳和沉积物揭示千年尺度的气候变化
7. Genomic architecture of a genetically assimilated seasonal color pattern
   基因同化，人工选择 regulatory allele 使一种蝴蝶的翅膀颜色从环境决定变成基因决定
8. Free fatty acid binding pocket in the locked structure of SARS-CoV-2 spike protein
   2.85A电镜，新冠S蛋白有三个亚油酸结合口袋，结合后进入“锁”构象，与ACE2的相互作用减弱



# Nature

01. A bright millisecond-duration radio burst from a Galactic magnetar
    磁星，快速射电暴
02. A fast radio burst associated with a Galactic magnetar
    同一颗星，同一个事件
03. No pulsed radio emission during a bursting phase of a Galactic magnetar
    观测数据，这个人正好在事件发生时没有观测
04. The impact of nuclear shape on the emergence of the neutron dripline
    新的模型，解释给定的元素到底能容纳多少中子
05. Logic-in-memory based on an atomically thin semiconductor
    把CPU和内存放在一起，很多人研究架构设计，作者关注具体实现的物质材料
06. An unexpectedly large count of trees in the West African Sahara and Sahel
    （沙漠中）独木虽然不成林，但作用也不能忽视啊
07. 150 million years of sustained increase in pterosaur flight efficiency
    翼龙是怎么学会飞翔的，其实不知道，但是发现即使再飞翔出现之后，飞翔效率也一直被大自然所优化
08. Memory failure predicted by attention lapsing and media multitasking
    多任务处理影响记忆
09. Quinone perception in plants via leucine-rich-repeat receptor-like kinases
    如何感应醌，植物有自己的一套，作者筛到了一个基因
10. snRNA-seq reveals a subpopulation of adipocytes that regulates thermogenesis
    单细胞核测序，发现一种稀有的脂肪细胞类型，抑制其它脂肪细胞的产热能力
11. A single bacterial genus maintains root growth in a complex microbiome
    植物根际有这么多细菌，但真正干活的只有其中一个属
12. Cytoplasmic control of intranuclear polarity by human cytomegalovirus
    细胞核是如何“炼成”的，看看巨病毒如何控制这一过程
13. TGF-β suppresses type 2 immunity to cancer
    I型免疫是杀灭敌人，Ⅱ型免疫是修复自己；敲除TGF-β之后后者增强，癌症遭殃
14. Cancer immunotherapy via targeted TGF-β signalling blockade in TH cells
    通讯都是同一人，不过这个摘要就说明了先后顺序，发现原理之后做了一系列抗癌实验
15. Pervasive chromosomal instability and karyotype order in tumour evolution
16. Modulating TRADD to restore cellular homeostasis and inhibit apoptosis
    恢复稳态，避免毁灭（凋亡）
17. The landscape of RNA Pol II binding reveals a stepwise transition during ZGA
    颉伟老师，没啥意外发现啊
18. A protein assembly mediates Xist localization and gene silencing
    Xist招募一堆 E-repeat-binding 蛋白形成复合体，形成之后不需要 Xist 也能维持
19. Single-particle cryo-EM at atomic resolution
20. Atomic-resolution protein structure determination by cryo-EM
