---
title: About
date: '2016-05-05'
author: Zhuoer Dong
slug: "about"
tags: 
  - to revise
---


# 临时简历

董卓尔

## 联系方式

Email：dongzhuoer@mail.nankai.edu.cn；主页：暂无；现居住于中国天津

## 研究兴趣

数据可视化，系统发育基因组学，研究流程自动化

## 教育背景

2014.09 ~         中国南开大学生命科学学院，本科生

## 获得奖励

2016.10 international Genetically Engineered Machine Competition Gold Award  
2015.10 2014--2015学年度南开大学综合一等奖学金 

## 工作经历

### 工作

暂无

### 实习

暂无

### 网站建设与管理

* 2016.06 ~ 2016.10 南开大学2016iGEM队伍wiki：http://2016.igem.org/Team:NKU_China

### 编程咨询

混迹GitHub等各种网站，暂未回答各种相关问题。

## 计算机水平

擅长使用网页制作软件（已忘光），以及数学模型求解、统计编程

* 数学软件：熟悉Mathematica；玩过MATLAB，已弃用 SPSS
* 语言：熟悉 R 语言，精通C++（已忘光），掌握网页语言 HTML、CSS、JavaScript，以及 Bash 脚本
* 应用程序：R语言IDE RStudio，六指琴魔Vim，版本控制系统Git，微软战略级武器Visual Studio（已弃用，居然不提供离线版下载了），不使用微软 Office
* 操作系统：日常使用Windows和Ubuntu MATE，从不使用OS X（买不起）
* 计算机等级：无任何等级证书（死记硬背早已落伍的知识不是虚度光影，而是谋财害命啊），但在本科期间修理过若干台个人电脑（软件层面），追求在实际工作中大量使用自动化脚本来提高工作效率（怎么能忍心与计算机抢饭碗呢）

## 个人原则

软件黑名单（我绝对不用的软件）：迅雷，各种管家卫士，各种视频客户端，国产浏览器，MS Office  
软件灰名单（我尽量避免的软件）：QQ，  
我的软件观：不让离线安装的一律毙掉，最好能portable，  
我的科学观：我对自然科学的兴趣远高于社会科学（根本不懂啊）。  
近期目标：希望以后能不需要WPS Office的编辑功能（告别Office）


## 英语水平

听力略有不足（听讲座），口语更加糟糕（靠表情），阅读勉强还行（[BingDict](https://www.bing.com/dict/)），写作乐此不疲（没人看）。


## 软件成果


### R 包

#### 作为主要作者：

bioinfor：生物信息学小函数  
phylobat：批量处理系统发育树


#### 作为贡献者：




### 其它

添加文件关联的Windows 注册表文件  
各种软件安装脚本，包括shell script和cmd


