---
title: 10-bit 色深还是不如 4K 好用啊
author: Zhuoer Dong
date: '2019-11-09'
slug: 10-bit-色深还是不如-4k-好用啊
categories: 2019
tags: []
authors: []
---



最近实验室经费比较充裕，老师想提升做计算同学的配置，大家就集中买了几台显示器。我挑了半天，看中了一款飞利浦的，因为比戴尔便宜，更支持 10-bit 色深。结果鼓捣了半天都没设置好，只好把探索经历记下来，希望以后硬件升级后能支持 ^[真不如像某师兄一样买一个 4K 的，当时一方面不好意思买太贵的，另一方面担心 Matebook 的 HDMI 端口不支持。但后来买了个 Dell Micro， 人家直接提供 Display Port，10-bit 则遥遥无期。]。

- Ubuntu 的 Nvidia 不能为两个显示器应用不同设置，只有 `X Screen 0` (虚拟的大屏幕) 支持 `1.1 Billion Colors (Depth 30) - Experimental`，但应用后 UI 好像变小了。
- 跑到 Windows，更坑了，默认都是核显，只有在需要时自动为特定软件使用独显（尝试 MX 150 设为默认显卡但失败了）。而且我的 Nvidia setting 是被简yan化ge过的，只有 `3D 设置`，别人的教程都是在这里可以调颜色深。顺便提一句，没想到自带显示屏居然只有 6位，看来外接显示屏能显示 8位已经进步不少了。
- 又回到 Ubuntu，想自己写配置文件，但我连 `/etc/X11/xorg.conf` 都找不到，放狗也搜不到 Ubuntu MATE 19.10 的 `xorg.conf` 路径。`sudo nvidia-xconfig` 倒是能生成一个，但我又不知道具体语法，根本无法改成我需要的样子（一个 8-bit，一个10-bit）。最后 `xdpyinfo` 给出了一大堆 `visual`，有 `8 bits` 也有 `11-bits`，我就假装默认是支持的吧。
- 后来发现
  + `X Screen 0` 的 `Depth 30` 无法保存，重启后就没了
  + `sudo systemctl restart display-manager` 可以刷新 Xorg 而不需要重启 OS
  + UI 变小是因为开机时连着 HDMI，把 HMDI 拔了之后刷新 Xorg 就好了
- 2019-11-29 又花了一节课，留点东西作为参考： boot in terminal mode `X -configure`
  ```
  Section "Screen"
  Identifier "Screen0"
  Device "Device0"
  Monitor "Monitor0"
  DefaultDepth 24
  SubSection "Display"
  Depth 24
  EndSubSection
  EndSections
  ```


