---
title: 三打 Ubuntu，失败的系统安装各有理由
author: Zhuoer Dong
date: '2019-11-21'
slug: 三打-ubuntu-失败的系统安装各有理由
tags: []
authors: []
---



# Preface

从上次 post（Minimo 主题）已经过去了一个半月，今天终于能抽出时间写新 post 了，还是走了后门的（还有三篇在 `draft.md` 排队呢）。我倒不至于那么忙，主要是优先搬砖（不被打扰时）、整理时又觉得写 post 太花时间，而今天实在不想再拖下去了。



# 一装 Ubuntu —— 先拿 Dell 试试手

Ubuntu 19.10 发布之后，我打算先在 Dell 上测试一下，顺便实现在宿舍也能继续搬砖 ^[带着 matebook 往返太麻烦了，虽然我买了额外的电源适配器放在宿舍，但还是孑然一身最轻松。]。同时我也想体验一下原生 Ubuntu，Ubuntu MATE 毕竟在上面额外加了一层，放狗搜帮助有时会遇到麻烦；况且我现在桌面的 top bar 还是浪费了垂直空间（多显示一行代码是一行），16:9 的屏幕就应该牺牲水平空间，Ubuntu 的 Dash 就蛮好的。

10 月 24 日动手安装，失败了好多次，终于找到 Rufus 启动盘格式和 BIOS 模式的正确搭配。

10 月 26 日开始研究解放垂直空间，主要是用 Gnome Tweak 设置 Gnome shell extension。问题在于：

- Dash 中同一程序的不同窗口合在一起，切换非常不方便（尤其是 VSCode，我至少会打开两个），之前 Ubuntu MATE 的 windows list indicator 就很好用，甚至 Windows 的任务栏都很容易设置为“不合并”。
- Ubuntu 的 top bar 只在左中右有东西，很浪费垂直空间， 应用程序的 title bar 更是如此，只有右边三个按钮有点用 ^[最小化、最大化、关闭，其实用处可不止一点，我探究时一度让 title bar 整个消失，结果没了这三个按钮真的很不方便。]。

最后用两个 extension 把 title bar 整合到 top bar，再把 top bar 整合进 Dash。这样很多常用程序（如 VSCode、RStudio、Caja）都可以节约垂直空间，而另一些（如 Chrome、WPS）保持不变，水平空间牺牲一些也无妨。

11 月 03 日把 Ubuntu 配置成可以干活的状态，果然非常麻烦，实质就是先有鸡还是先有蛋的难题（各种循环依赖）。而且这次还是完全从头开始（以前文件都在一块独立分区），花了不少时间，探索出一种基于 GitHub project 的安装教程。

另外换了一种 Dash 实现方式：

- dash to panel 扩展放在左边，显示打开的应用 ^[后来在 Matebook 上应用时，发现可以 `Ungrouped`，彻底舒服了。]，就像 Windows 任务栏
- dash to dock 扩展自动隐藏到下面，显示收藏的应用，就像 Windows metro



# 二装 Ubuntu —— 都是 `nouveau` 惹的祸

本来想等文件都整理完（完全 Git 化），再把 Ubuntu 应用到 Matebook。但 11 月 17 日实在忍不了了，与其一直往后拖，还不如反过来，用装系统 push 我整理文件。这次收获的经验了如下：

- 其实不存在一个线性的操作顺序，因为有很多循环依赖
- 不要总想着把某一步跑起来之后，就可以在等待时做很多事
- 有些需要重启或重新 login 的确实很烦
- recovery back 与其依赖脚本，还不如 `code /path/to/config` 加复制粘贴

第一次安装很卡，Settings 到最后一项 Details 时，系统完全卡死，只能强制关机。开机后，Settings 一直打不开，到后面又卡死了。

第二天重装了一次，还是 Details 卡死，就放狗搜（还好有台 iMac 能**上网**），居然是 Ubuntu 的 bug。

看来我还是太依赖 GUI 了，我当时能看到有好几个 `gnome-control-center`，但只会把它们 kill 掉；别人则在 command line 调用 `gnome-control-center --verbose` 来查看 log，发现 `Segmentation fault (core dumped)`。另外还有一个关于 Pos_OS 的，说是要安装 `hidpi-daemon`，但 Ubuntu 没有。

然后我又更换关键词，强调 `ubuntu 19.10 gnome`，而且已知是 `setting devices` 的问题，终于找到了有用的[回答](https://askubuntu.com/questions/1182647/#answer-1183137)。原来是要安装 NVIDIA 的驱动啊，之前的卡死都是开源驱动 `nouveau` 惹的祸。

但 `apt` 列出了好多版本，干脆重装一次系统吧，正好测试一下在安装时就选上 `third-party`。其实我第一次在 Matebook 上装 Ubuntu mate 是选了的，不知道这次是哪根筋不对，没有勾选 ^[可能是觉得选上会等好久，但其实不选也得等一会。]。

然后就 happy end 了。



# 三装 Ubuntu —— NVMe 也是一把双刃剑

自从上上周六外接显示器到货之后，Matebook，经常热得风扇转起来，而且电量耗得很快，总是要插拔电源。尤其是改成 Ubuntu 19.04 之后，待机非常不方便，需要先锁屏、再 sleep，而且启动时还要输入密码。

11 月 20 日在京东逛微型主机，发现 Dell OptiPlex 7070 降价三四千。开始我还担心是质量问题，就想找出降价的原因（比如做活动），发现同一系列几款都在降、另几款则是原件，美国官网也同样如此。看起来应该不是质量问题，那就赶紧剁手呀，这优惠幅度谁能扛得住哦。

于是跑到京东下单（当天送到它不香吗），在 Dell 官网比较了一下配置，机械硬盘是不可能的，还有的优惠相对不划算，就买个最便宜的 ￥3599 （i5 + 8G + 256G），还能享受京东物流。临下单前又反思了一下，这应该是我博士期间最后一台高配电脑 ^[再买一台就真是太奢侈了，除非能发 CNS。]，还是要买一个能撑四五年的才行，就换了 ￥4699 的（i7 + 8G + 256G）。卖家的花招果然防不胜防，付款时只能选则快递配送，卖家说也可以发京东，我就相信了；但后来又说当天只能把货给京东，也就是不能享受当天送到，我就让卖家换成顺丰了。

11月 21 日上午到货，赶紧安装 Ubuntu，但插入启动盘后没有列出 SSD，这就搞笑了，总不能装在 U 盘上吧。还是先进入自带的 Windows，明明就有 256G 的 SSD 可用啊。放狗一搜，原来是要在 BIOS 关闭 RAID，Windows 就是喜欢和 Intel 穿一条裤子，不让用户安装别的系统。装好后开机，一直停留在 Ubuntu logo 加省略号的界面，我中午吃饭回来都没好。看来是没救了，反正也没有配置，直接重装吧，依然开不了机。我一怒之下把 Windows 彻底删除，重新给磁盘分区，还是不行。这下舒服了，都不能无理由退货了。

后来发现开机时编辑启动选项，在 `quiet` 后加上 `3` 可以进入命令行模式。`startx` 报错，加上 `sudo` 就成功了，终于可以看到 desktop 了，但问题还是没有解决。又放狗搜了一下，在 `/etc/default/grub` 中去掉 `quiet splash`，可以在开机时显示 log （而不是该死的 Ubuntu logo 加省略号）。正当我想要对 log 针对性地 debug 时，突然一切正常了。所以这是孩子咳嗽老不好，×了就好了吗？



# 后记

这篇 post拖了很久，当时只来得及写到 “11 月 03 日”，后面内容都是 draft（很多省略号，语句也不通顺），11 月 26 下午花了~~两节课~~两小时才彻底完成。我觉得博客最重要的作用还是自我反思 ^[如果是为了给别人看，我现在可没有资格浪费这么多时间。]。

比如 Matebook，我上网查了一下，一直插上电源线的话，并不会给电池充放电，对寿命的影响不是特别大。退一步说，我几乎不会把电脑带到没有插座的地方；再退一步，毕业时换块新电池也花不了多少钱。也就是说 Dell Micro 并没有起到多少实质性的作用（反倒是 8G 内存真不要太卡），花的钱倒不算太亏（毕竟大降价），时间才是最宝贵的啊。

这次就先这样了，以后要吸取教训，遇到困难不要着急去解决，专心推动项目进展才是正事。




